--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/padreon/TittleADR
branches:
- master
projects:
  TittleADR:
    path: ""

    libs:
      - src: jojoe77777\FormAPI\FormAPI
        version: ^1.3.0
...
